### ISSUE TITLE
Couldn't change the appointment

### ISSUE THREAD

**Issue by Frankkkkie** [Zaichenko-Vladyslav/USA-VISA-BOT#1]
Hi Zaichenko, I am using your bot which is good. But It seems the bot could't automatically change the apponintment. I am tring to read the code and I found the row 255 variaty: FACILITY_ID is not be defined. Could It be the issue?

**Comment by Frankkkkie** [comment]
I made some changes on main()

async function main(currentAppointmentDate) {

  if (!currentAppointmentDate) {
    console.log(`Invalid current appointment date: ${currentAppointmentDate}`)
    process.exit(1)
  }

  console.log(`Current appointment date: ${currentAppointmentDate}`)

  try {

    while (!bestAvailableDate) {

      const sessionHeaders = await authentication()
      const currentDate = new Date()
      const formatedDate = currentDate.toLocaleString()

      console.log(`Authentication process - OK. Current Date and Time: ${formatedDate}`)

      for (const {id, name: embassy_name} of listOfEmbassies) {

        const date = await findAvailableDate(sessionHeaders, id);
  
        if (!date) {
          console.log(`Embassy: ${embassy_name}. Status: No available dates found!`);
        } else if (date > currentAppointmentDate) {
          console.log(`Embassy: ${embassy_name}. Status: Nearest date ${date} is further than already booked!`);
        } else {
  
          const time = await findAvailableTime(sessionHeaders, date, id);
  
          console.log(`Embassy - ${embassy_name}. Status: Closest date and time: ${date} (${time})`);
          
          if (!bestAvailableDate || (date < bestAvailableDate)) {
            bestAvailableEmbassy = embassy_name;
            bestAvailableDate = date;
            bestAvailableTime = time;

          }
        }
      }

      if (bestAvailableDate) {

        const emailContent = `Best available date across all embassies found! Embassy: ${bestAvailableEmbassy}, date and time: ${bestAvailableDate} (${bestAvailableTime})`;
        console.log(emailContent);
  
        const message = {
          to: NOTIFICATION_EMAIL,
          from: NOTIFICATION_EMAIL,
          subject: 'USA VISA Appointment available date found!',
          text: emailContent,
        }
  
        sgMail.send(message)
          .then((response) => {
            console.log(response[0].statusCode)
            console.log(response[0].headers)
          })
          .catch(error => log(`Error sending email: ${error.message}`));
  
        console.log(bestAvailableDate, bestAvailableTime)
  
        // Book New Appointment
        console.log('Attempt to book new appointment!')
        bookAppointment(sessionHeaders, bestAvailableDate, bestAvailableTime)
          .then(d => console.log(`New appointent booked! Date and time: ${bestAvailableDate} (${bestAvailableTime})`))
  
      } 

        
      console.log('Wait for ' + 3 + ' minutes!')
      await sleep(60 * 3);

    }


  } catch (error) {
    console.error(error)
    main(currentAppointmentDate)
  }
}

**Comment by Zaichenko-Vladyslav** [comment]
Hi 👋

Sorry for the delay with my answer!

I am happy that you found this application useful. Thank you for reporting this issue!

In the first version, I used notifications only and got an appointment rescheduled a few times. In the second version, I added functionality for automatically rescheduling. Unfortunately, I did not have a chance to test it, no available spots were found after that.

Facility ID issue is fixed now, you can pull updated code. Good luck 😉

With best regards,
Vladyslav Zaichenko
